public class MyClass { 
    public final boolean b = true;
    integer t = 12;
    double dfa { 
        public get { return 10.00; }  
        private set { dfa = 1.12; }
    }
    public long l = 1231123L;
    public string myvar {
        get;
        set { myvar = 'Hello, World!'; }
    }
    public static id myobjId = '00300000003T2PGAA0';

}

public static class MyClass2 {
    class MemberClass { }

    class MemberClass2 { 
        double k = 12.21;
    }
}


public class MyClass3 {
    public interface PurchaseOrder {}

    public interface PurchaseOrder2 {
        Double discount();
    }
}

public class MyClass4 {
    MyClass4(){
        
    }
}